/**
 * ============================================================================
 * Honor Pole Innovations
 * HonorPole Platform
 * ----------------------------------------------------------------------------
 * File: DiagnosticEntry.ts
 *
 * Description:
 * Represents a single diagnostic event generated by the HonorPole platform.
 * This class is a pure domain entity and contains no UI, networking,
 * firmware, or logging logic.
 * ============================================================================
 */

import { DiagnosticSeverity } from "./DiagnosticSeverity";
import { DiagnosticCategory } from "./DiagnosticCategory";

/**
 * Represents a single diagnostic event.
 */
export class DiagnosticEntry {

    //--------------------------------------------------------------------------
    // Private Fields
    //--------------------------------------------------------------------------

    private readonly _firstOccurred: Date;

    private _lastOccurred: Date;

    private readonly _severity: DiagnosticSeverity;

    private readonly _category: DiagnosticCategory;

    private readonly _code: string;

    private readonly _message: string;

    private _occurrences: number;

    private _active: boolean;

    private _acknowledged: boolean;

    private _clearedAt?: Date;

    //--------------------------------------------------------------------------
    // Constructor
    //--------------------------------------------------------------------------

    constructor(
        severity: DiagnosticSeverity,
        category: DiagnosticCategory,
        code: string,
        message: string
    ) {

        const now = new Date();

        this._firstOccurred = now;
        this._lastOccurred = now;

        this._severity = severity;
        this._category = category;

        this._code = code.trim();
        this._message = message.trim();

        this._occurrences = 1;

        this._active = true;

        this._acknowledged = false;

        this._clearedAt = undefined;
    }

    //--------------------------------------------------------------------------
    // Public Properties
    //--------------------------------------------------------------------------

    public get firstOccurred(): Date {
        return this._firstOccurred;
    }

    public get lastOccurred(): Date {
        return this._lastOccurred;
    }

    public get severity(): DiagnosticSeverity {
        return this._severity;
    }

    public get category(): DiagnosticCategory {
        return this._category;
    }

    public get code(): string {
        return this._code;
    }

    public get message(): string {
        return this._message;
    }

    public get occurrences(): number {
        return this._occurrences;
    }

    public get active(): boolean {
        return this._active;
    }

    public get acknowledged(): boolean {
        return this._acknowledged;
    }

    public get clearedAt(): Date | undefined {
        return this._clearedAt;
    }

    /**
     * Age of this diagnostic in milliseconds.
     */
    public get age(): number {
        return Date.now() - this._firstOccurred.getTime();
    }

    //--------------------------------------------------------------------------
    // Public Methods
    //--------------------------------------------------------------------------

    /**
     * Indicates whether this entry matches another diagnostic code.
     */
    public matches(code: string): boolean {

        return this._code === code;

    }

    /**
     * Registers another occurrence of this diagnostic.
     */
    public incrementOccurrence(): void {

        this._occurrences++;

        this._lastOccurred = new Date();

    }

    /**
     * Marks this diagnostic as acknowledged.
     */
    public acknowledge(): void {

        this._acknowledged = true;

    }

    /**
     * Clears the diagnostic.
     *
     * Calling this multiple times has no effect.
     */
    public clear(): void {

        if (!this._active) {
            return;
        }

        this._active = false;

        this._clearedAt = new Date();

        this._lastOccurred = this._clearedAt;

    }
    /**
     * Returns true if this is an informational diagnostic.
     */
    public isInformation(): boolean {

        return this._severity === DiagnosticSeverity.Information;

    }

    /**
     * Returns true if this is a warning diagnostic.
     */
    public isWarning(): boolean {

        return this._severity === DiagnosticSeverity.Warning;

    }

    /**
     * Returns true if this is an error diagnostic.
     */
    public isError(): boolean {

        return this._severity === DiagnosticSeverity.Error;

    }

    /**
     * Returns true if this is a critical diagnostic.
     */
    public isCritical(): boolean {

        return this._severity === DiagnosticSeverity.Critical;

    }

    /**
     * Returns a serializable representation of this diagnostic.
     */
    public toJSON() {

        return {

            firstOccurred: this._firstOccurred,

            lastOccurred: this._lastOccurred,

            severity: this._severity,

            category: this._category,

            code: this._code,

            message: this._message,

            occurrences: this._occurrences,

            active: this._active,

            acknowledged: this._acknowledged,

            clearedAt: this._clearedAt,

            age: this.age

        };

    }

}